name: Prepare Android project (TWA)
on:
  workflow_dispatch:
jobs:
  prepare-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Android project (PWABuilder)
        run: |
          URL="https://cookiegamemaster59-del.github.io/Blitzer.EE/"
          curl -L "https://www.pwabuilder.com/api/android?site=${URL}" -o android-project.zip
      - name: Create GitHub Release (Android Project)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-proj-${{ github.run_id }}
          name: Android Project ${{ github.run_id }}
          draft: false
          prerelease: true
          files: |
            android-project.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
